// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StatisticsApi.Context;

#nullable disable

namespace StatisticsApi.Migrations
{
    [DbContext(typeof(StatisticsDbContext))]
    partial class StatisticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.BattleRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BattleInstanceId")
                        .HasColumnType("integer");

                    b.Property<int>("Character1CardsPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("Character1DamageDealt")
                        .HasColumnType("integer");

                    b.Property<bool>("Character1Downed")
                        .HasColumnType("boolean");

                    b.Property<int>("Character1HpEnd")
                        .HasColumnType("integer");

                    b.Property<int>("Character1HpStart")
                        .HasColumnType("integer");

                    b.Property<int>("Character2CardsPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("Character2DamageDealt")
                        .HasColumnType("integer");

                    b.Property<bool>("Character2Downed")
                        .HasColumnType("boolean");

                    b.Property<int>("Character2HpEnd")
                        .HasColumnType("integer");

                    b.Property<int>("Character2HpStart")
                        .HasColumnType("integer");

                    b.Property<int>("Character3CardsPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("Character3DamageDealt")
                        .HasColumnType("integer");

                    b.Property<bool>("Character3Downed")
                        .HasColumnType("boolean");

                    b.Property<int>("Character3HpEnd")
                        .HasColumnType("integer");

                    b.Property<int>("Character3HpStart")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterResting")
                        .HasColumnType("integer");

                    b.Property<int>("FloorEncountered")
                        .HasColumnType("integer");

                    b.Property<int>("GoldGained")
                        .HasColumnType("integer");

                    b.Property<int>("LevelEncountered")
                        .HasColumnType("integer");

                    b.Property<int>("RoundsElapsed")
                        .HasColumnType("integer");

                    b.Property<int>("TeamworkEnd")
                        .HasColumnType("integer");

                    b.Property<int>("TeamworkStart")
                        .HasColumnType("integer");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer");

                    b.Property<bool>("WonBattle")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BattleInstanceId");

                    b.HasIndex("VersionId");

                    b.ToTable("BattleRecords");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.CardChoiceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CardPickedId")
                        .HasColumnType("integer");

                    b.Property<bool>("DuplicatePicked")
                        .HasColumnType("boolean");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("integer");

                    b.Property<int>("LevelNumber")
                        .HasColumnType("integer");

                    b.Property<int>("RerollCount")
                        .HasColumnType("integer");

                    b.Property<int?>("RewardRecordId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamworkSpent")
                        .HasColumnType("integer");

                    b.Property<bool>("UpgradePicked")
                        .HasColumnType("boolean");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardPickedId");

                    b.HasIndex("RewardRecordId");

                    b.HasIndex("VersionId");

                    b.ToTable("CardChoiceRecords");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.CardRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CardInstanceId")
                        .HasColumnType("integer");

                    b.Property<int?>("CharacterRecordId")
                        .HasColumnType("integer");

                    b.Property<int>("PartySlot")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardInstanceId");

                    b.HasIndex("CharacterRecordId");

                    b.ToTable("CardRecords");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.CharacterRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterInstanceId")
                        .HasColumnType("integer");

                    b.Property<int?>("GameResultId")
                        .HasColumnType("integer");

                    b.Property<int>("PartySlot")
                        .HasColumnType("integer");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterInstanceId");

                    b.HasIndex("GameResultId");

                    b.HasIndex("VersionId");

                    b.ToTable("CharacterRecords");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.EventRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChoiceSelected")
                        .HasColumnType("integer");

                    b.Property<int>("EventInstanceId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamworkOnEnter")
                        .HasColumnType("integer");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventInstanceId");

                    b.HasIndex("VersionId");

                    b.ToTable("EventRecords");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.GameResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Abandoned")
                        .HasColumnType("boolean");

                    b.Property<int>("GameVersionId")
                        .HasColumnType("integer");

                    b.Property<int>("LevelsCompleted")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("RemainingGold")
                        .HasColumnType("integer");

                    b.Property<int>("RemainingTeamwork")
                        .HasColumnType("integer");

                    b.Property<int>("RoomsCompleted")
                        .HasColumnType("integer");

                    b.Property<string>("RunPerk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalGoldEarned")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTeamworkEarned")
                        .HasColumnType("integer");

                    b.Property<bool>("Win")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("GameVersionId");

                    b.ToTable("GameResults");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.GameVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("VersionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GameVersions");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Instances.BattleInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BattleInstances");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Instances.CardInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CardInstances");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Instances.CharacterInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CharacterInstances");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Instances.EventChoiceInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventChoiceInstance");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Instances.EventInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EventInstances");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Instances.PassiveInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rarity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PassiveInstances");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.PassiveRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("GameResultId")
                        .HasColumnType("integer");

                    b.Property<int>("PartySlot")
                        .HasColumnType("integer");

                    b.Property<int>("PassiveInstanceId")
                        .HasColumnType("integer");

                    b.Property<int?>("RewardRecordId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameResultId");

                    b.HasIndex("PassiveInstanceId");

                    b.HasIndex("RewardRecordId");

                    b.ToTable("PassiveRecords");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Relationships.CardChoiceCardInstance", b =>
                {
                    b.Property<int>("CardChoiceRecordId")
                        .HasColumnType("integer");

                    b.Property<int>("CardInstanceId")
                        .HasColumnType("integer");

                    b.HasKey("CardChoiceRecordId", "CardInstanceId");

                    b.HasIndex("CardInstanceId");

                    b.ToTable("CardChoiceCards");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Relationships.RerolledCardCardInstance", b =>
                {
                    b.Property<int>("CardChoiceRecordId")
                        .HasColumnType("integer");

                    b.Property<int>("CardInstanceId")
                        .HasColumnType("integer");

                    b.HasKey("CardChoiceRecordId", "CardInstanceId");

                    b.HasIndex("CardInstanceId");

                    b.ToTable("RerolledCardCardInstances");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Relationships.RewardGivenTradeCards", b =>
                {
                    b.Property<int>("RewardRecordId")
                        .HasColumnType("integer");

                    b.Property<int>("CardRecordId")
                        .HasColumnType("integer");

                    b.HasKey("RewardRecordId", "CardRecordId");

                    b.HasIndex("CardRecordId");

                    b.ToTable("RewardGivenTradeCards");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Relationships.RewardJunkCards", b =>
                {
                    b.Property<int>("RewardRecordId")
                        .HasColumnType("integer");

                    b.Property<int>("CardRecordId")
                        .HasColumnType("integer");

                    b.HasKey("RewardRecordId", "CardRecordId");

                    b.HasIndex("CardRecordId");

                    b.ToTable("RewardJunkCards");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Relationships.RewardRecievedTradeCards", b =>
                {
                    b.Property<int>("RewardRecordId")
                        .HasColumnType("integer");

                    b.Property<int>("CardRecordId")
                        .HasColumnType("integer");

                    b.HasKey("RewardRecordId", "CardRecordId");

                    b.HasIndex("CardRecordId");

                    b.ToTable("RewardRecievedTradeCards");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Relationships.RewardRemovedCards", b =>
                {
                    b.Property<int>("RewardRecordId")
                        .HasColumnType("integer");

                    b.Property<int>("CardRecordId")
                        .HasColumnType("integer");

                    b.HasKey("RewardRecordId", "CardRecordId");

                    b.HasIndex("CardRecordId");

                    b.ToTable("RewardRemovedCards");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Relationships.RewardUpgradedCards", b =>
                {
                    b.Property<int>("RewardRecordId")
                        .HasColumnType("integer");

                    b.Property<int>("CardRecordId")
                        .HasColumnType("integer");

                    b.HasKey("RewardRecordId", "CardRecordId");

                    b.HasIndex("CardRecordId");

                    b.ToTable("RewardUpgradedCards");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Relationships.ShopAffordableCard", b =>
                {
                    b.Property<int>("ShopRecordId")
                        .HasColumnType("integer");

                    b.Property<int>("CardInstanceId")
                        .HasColumnType("integer");

                    b.HasKey("ShopRecordId", "CardInstanceId");

                    b.HasIndex("CardInstanceId");

                    b.ToTable("ShopAffordableCards");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Relationships.ShopAffordablePassive", b =>
                {
                    b.Property<int>("ShopRecordId")
                        .HasColumnType("integer");

                    b.Property<int>("PassiveInstanceId")
                        .HasColumnType("integer");

                    b.HasKey("ShopRecordId", "PassiveInstanceId");

                    b.HasIndex("PassiveInstanceId");

                    b.ToTable("ShopAffordablePassives");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Relationships.ShopPurchasedCard", b =>
                {
                    b.Property<int>("ShopRecordId")
                        .HasColumnType("integer");

                    b.Property<int>("CardInstanceId")
                        .HasColumnType("integer");

                    b.HasKey("ShopRecordId", "CardInstanceId");

                    b.HasIndex("CardInstanceId");

                    b.ToTable("ShopPurchasedCards");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Relationships.ShopPurchasedPassive", b =>
                {
                    b.Property<int>("ShopRecordId")
                        .HasColumnType("integer");

                    b.Property<int>("PassiveInstanceId")
                        .HasColumnType("integer");

                    b.HasKey("ShopRecordId", "PassiveInstanceId");

                    b.HasIndex("PassiveInstanceId");

                    b.ToTable("ShopPurchasedPassives");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.RewardRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GoldGained")
                        .HasColumnType("integer");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VersionId");

                    b.ToTable("RewardRecords");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.RoomRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BattleRecordId")
                        .HasColumnType("integer");

                    b.Property<int?>("EventRecordId")
                        .HasColumnType("integer");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("GameResultId")
                        .HasColumnType("integer");

                    b.Property<int>("LevelNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("RewardRecordId")
                        .HasColumnType("integer");

                    b.Property<int?>("ShopRecordId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BattleRecordId");

                    b.HasIndex("EventRecordId");

                    b.HasIndex("GameResultId");

                    b.HasIndex("RewardRecordId");

                    b.HasIndex("ShopRecordId");

                    b.ToTable("RoomRecords");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.ShopRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GoldEntered")
                        .HasColumnType("integer");

                    b.Property<int>("GoldSpent")
                        .HasColumnType("integer");

                    b.Property<bool>("UpgradePurchased")
                        .HasColumnType("boolean");

                    b.Property<int?>("UpgradedCardId")
                        .HasColumnType("integer");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UpgradedCardId");

                    b.HasIndex("VersionId");

                    b.ToTable("ShopRecords");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.BattleRecord", b =>
                {
                    b.HasOne("EscapeFromTrinityEngineStats.Models.Instances.BattleInstance", "BattleInstance")
                        .WithMany()
                        .HasForeignKey("BattleInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscapeFromTrinityEngineStats.Models.GameVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BattleInstance");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.CardChoiceRecord", b =>
                {
                    b.HasOne("EscapeFromTrinityEngineStats.Models.Instances.CardInstance", "CardPicked")
                        .WithMany()
                        .HasForeignKey("CardPickedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscapeFromTrinityEngineStats.Models.RewardRecord", null)
                        .WithMany("CardChoiceRecords")
                        .HasForeignKey("RewardRecordId");

                    b.HasOne("EscapeFromTrinityEngineStats.Models.GameVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardPicked");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.CardRecord", b =>
                {
                    b.HasOne("EscapeFromTrinityEngineStats.Models.Instances.CardInstance", "CardInstance")
                        .WithMany()
                        .HasForeignKey("CardInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscapeFromTrinityEngineStats.Models.CharacterRecord", null)
                        .WithMany("DeckRecord")
                        .HasForeignKey("CharacterRecordId");

                    b.Navigation("CardInstance");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.CharacterRecord", b =>
                {
                    b.HasOne("EscapeFromTrinityEngineStats.Models.Instances.CharacterInstance", "CharacterInstance")
                        .WithMany()
                        .HasForeignKey("CharacterInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscapeFromTrinityEngineStats.Models.GameResult", null)
                        .WithMany("Characters")
                        .HasForeignKey("GameResultId");

                    b.HasOne("EscapeFromTrinityEngineStats.Models.GameVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterInstance");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.EventRecord", b =>
                {
                    b.HasOne("EscapeFromTrinityEngineStats.Models.Instances.EventInstance", "EventInstance")
                        .WithMany()
                        .HasForeignKey("EventInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscapeFromTrinityEngineStats.Models.GameVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventInstance");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.GameResult", b =>
                {
                    b.HasOne("EscapeFromTrinityEngineStats.Models.GameVersion", "GameVersion")
                        .WithMany()
                        .HasForeignKey("GameVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameVersion");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Instances.EventChoiceInstance", b =>
                {
                    b.HasOne("EscapeFromTrinityEngineStats.Models.Instances.EventInstance", "Event")
                        .WithMany("EventChoices")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.PassiveRecord", b =>
                {
                    b.HasOne("EscapeFromTrinityEngineStats.Models.GameResult", null)
                        .WithMany("Passives")
                        .HasForeignKey("GameResultId");

                    b.HasOne("EscapeFromTrinityEngineStats.Models.Instances.PassiveInstance", "PassiveInstance")
                        .WithMany()
                        .HasForeignKey("PassiveInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscapeFromTrinityEngineStats.Models.RewardRecord", null)
                        .WithMany("PassiveRecords")
                        .HasForeignKey("RewardRecordId");

                    b.Navigation("PassiveInstance");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Relationships.CardChoiceCardInstance", b =>
                {
                    b.HasOne("EscapeFromTrinityEngineStats.Models.CardChoiceRecord", "CardChoiceRecord")
                        .WithMany("CardChoices")
                        .HasForeignKey("CardChoiceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscapeFromTrinityEngineStats.Models.Instances.CardInstance", "CardInstance")
                        .WithMany()
                        .HasForeignKey("CardInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardChoiceRecord");

                    b.Navigation("CardInstance");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Relationships.RerolledCardCardInstance", b =>
                {
                    b.HasOne("EscapeFromTrinityEngineStats.Models.CardChoiceRecord", "CardChoiceRecord")
                        .WithMany("RerolledCards")
                        .HasForeignKey("CardChoiceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscapeFromTrinityEngineStats.Models.Instances.CardInstance", "CardInstance")
                        .WithMany()
                        .HasForeignKey("CardInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardChoiceRecord");

                    b.Navigation("CardInstance");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Relationships.RewardGivenTradeCards", b =>
                {
                    b.HasOne("EscapeFromTrinityEngineStats.Models.CardRecord", "CardRecord")
                        .WithMany()
                        .HasForeignKey("CardRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscapeFromTrinityEngineStats.Models.RewardRecord", "RewardRecord")
                        .WithMany("GivenTradeCards")
                        .HasForeignKey("RewardRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardRecord");

                    b.Navigation("RewardRecord");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Relationships.RewardJunkCards", b =>
                {
                    b.HasOne("EscapeFromTrinityEngineStats.Models.CardRecord", "CardRecord")
                        .WithMany()
                        .HasForeignKey("CardRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscapeFromTrinityEngineStats.Models.RewardRecord", "RewardRecord")
                        .WithMany("JunkRewards")
                        .HasForeignKey("RewardRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardRecord");

                    b.Navigation("RewardRecord");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Relationships.RewardRecievedTradeCards", b =>
                {
                    b.HasOne("EscapeFromTrinityEngineStats.Models.CardRecord", "CardRecord")
                        .WithMany()
                        .HasForeignKey("CardRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscapeFromTrinityEngineStats.Models.RewardRecord", "RewardRecord")
                        .WithMany("RecievedTradeCards")
                        .HasForeignKey("RewardRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardRecord");

                    b.Navigation("RewardRecord");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Relationships.RewardRemovedCards", b =>
                {
                    b.HasOne("EscapeFromTrinityEngineStats.Models.CardRecord", "CardRecord")
                        .WithMany()
                        .HasForeignKey("CardRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscapeFromTrinityEngineStats.Models.RewardRecord", "RewardRecord")
                        .WithMany("RemovedCards")
                        .HasForeignKey("RewardRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardRecord");

                    b.Navigation("RewardRecord");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Relationships.RewardUpgradedCards", b =>
                {
                    b.HasOne("EscapeFromTrinityEngineStats.Models.CardRecord", "CardRecord")
                        .WithMany()
                        .HasForeignKey("CardRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscapeFromTrinityEngineStats.Models.RewardRecord", "RewardRecord")
                        .WithMany("UpgradedCards")
                        .HasForeignKey("RewardRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardRecord");

                    b.Navigation("RewardRecord");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Relationships.ShopAffordableCard", b =>
                {
                    b.HasOne("EscapeFromTrinityEngineStats.Models.Instances.CardInstance", "CardInstance")
                        .WithMany()
                        .HasForeignKey("CardInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscapeFromTrinityEngineStats.Models.ShopRecord", "ShopRecord")
                        .WithMany("AffordableCards")
                        .HasForeignKey("ShopRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardInstance");

                    b.Navigation("ShopRecord");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Relationships.ShopAffordablePassive", b =>
                {
                    b.HasOne("EscapeFromTrinityEngineStats.Models.Instances.PassiveInstance", "PassiveInstance")
                        .WithMany()
                        .HasForeignKey("PassiveInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscapeFromTrinityEngineStats.Models.ShopRecord", "ShopRecord")
                        .WithMany("AffordablePassives")
                        .HasForeignKey("ShopRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PassiveInstance");

                    b.Navigation("ShopRecord");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Relationships.ShopPurchasedCard", b =>
                {
                    b.HasOne("EscapeFromTrinityEngineStats.Models.Instances.CardInstance", "CardInstance")
                        .WithMany()
                        .HasForeignKey("CardInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscapeFromTrinityEngineStats.Models.ShopRecord", "ShopRecord")
                        .WithMany("PurchasedCards")
                        .HasForeignKey("ShopRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardInstance");

                    b.Navigation("ShopRecord");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Relationships.ShopPurchasedPassive", b =>
                {
                    b.HasOne("EscapeFromTrinityEngineStats.Models.Instances.PassiveInstance", "PassiveInstance")
                        .WithMany()
                        .HasForeignKey("PassiveInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscapeFromTrinityEngineStats.Models.ShopRecord", "ShopRecord")
                        .WithMany("PurchasedPassives")
                        .HasForeignKey("ShopRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PassiveInstance");

                    b.Navigation("ShopRecord");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.RewardRecord", b =>
                {
                    b.HasOne("EscapeFromTrinityEngineStats.Models.GameVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.RoomRecord", b =>
                {
                    b.HasOne("EscapeFromTrinityEngineStats.Models.BattleRecord", "BattleRecord")
                        .WithMany()
                        .HasForeignKey("BattleRecordId");

                    b.HasOne("EscapeFromTrinityEngineStats.Models.EventRecord", "EventRecord")
                        .WithMany()
                        .HasForeignKey("EventRecordId");

                    b.HasOne("EscapeFromTrinityEngineStats.Models.GameResult", null)
                        .WithMany("Rooms")
                        .HasForeignKey("GameResultId");

                    b.HasOne("EscapeFromTrinityEngineStats.Models.RewardRecord", "RewardRecord")
                        .WithMany()
                        .HasForeignKey("RewardRecordId");

                    b.HasOne("EscapeFromTrinityEngineStats.Models.ShopRecord", "ShopRecord")
                        .WithMany()
                        .HasForeignKey("ShopRecordId");

                    b.Navigation("BattleRecord");

                    b.Navigation("EventRecord");

                    b.Navigation("RewardRecord");

                    b.Navigation("ShopRecord");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.ShopRecord", b =>
                {
                    b.HasOne("EscapeFromTrinityEngineStats.Models.CardRecord", "UpgradedCard")
                        .WithMany()
                        .HasForeignKey("UpgradedCardId");

                    b.HasOne("EscapeFromTrinityEngineStats.Models.GameVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UpgradedCard");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.CardChoiceRecord", b =>
                {
                    b.Navigation("CardChoices");

                    b.Navigation("RerolledCards");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.CharacterRecord", b =>
                {
                    b.Navigation("DeckRecord");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.GameResult", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Passives");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.Instances.EventInstance", b =>
                {
                    b.Navigation("EventChoices");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.RewardRecord", b =>
                {
                    b.Navigation("CardChoiceRecords");

                    b.Navigation("GivenTradeCards");

                    b.Navigation("JunkRewards");

                    b.Navigation("PassiveRecords");

                    b.Navigation("RecievedTradeCards");

                    b.Navigation("RemovedCards");

                    b.Navigation("UpgradedCards");
                });

            modelBuilder.Entity("EscapeFromTrinityEngineStats.Models.ShopRecord", b =>
                {
                    b.Navigation("AffordableCards");

                    b.Navigation("AffordablePassives");

                    b.Navigation("PurchasedCards");

                    b.Navigation("PurchasedPassives");
                });
#pragma warning restore 612, 618
        }
    }
}
